### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Swiftyk7** [PartyPlanner64/PartyPlanner64#77]
If this isn't what I was supposed to do, then I apologize, but I'm not sure what happened. I clicked on a space and got this error:

TypeError: Cannot read property 'type' of undefined
Stack Error Details:
TypeError: Cannot read property 'type' of undefined
    at SpaceProperties../js/spaceproperties.tsx.SpaceProperties.render (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:26441:27)
    at finishClassComponent (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:103208:31)
    at updateClassComponent (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:103163:24)
    at beginWork (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:104111:16)
    at performUnitOfWork (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:107779:12)
    at workLoop (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:107819:24)
    at renderRoot (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:107902:7)
    at performWorkOnRoot (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:108809:7)
    at performWork (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:108721:7)
    at performSyncWork (file:///C:/Users/3020/AppData/Local/Programs/PartyPlanner64/resources/app.asar/js/app.min.js:108695:3)
Component Stack Error Details:

    in SpaceProperties (created by PP64App)
    in div (created by ToolWindow)
    in ToolWindow (created by PP64App)
    in div (created by PP64App)
    in div (created by PP64App)
    in div (created by PP64App)
    in div (created by PP64App)
    in PP64App

**Comment by PartyPlanner64** [comment]
Thanks for the report. I believe I have fixed the issue, which had to do with switching the currently visible board with selected spaces. Since it looks like you are using the Windows build, I pushed an update for that as well.
