### ISSUE TITLE
Somethin' wrong in Model Village

### ISSUE THREAD

**Issue by RainbowTHOfficial** [PartyPlanner64/PartyPlanner64#93]
After loading Megafruit Paradise, entering Model Viewer causes this crash:

`TypeError: Cannot read property 'decompressed' of undefined
Stack Error Details:
TypeError: Cannot read property 'decompressed' of undefined
    at Function.value (file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/main.8c016716.chunk.js:1:414670)
    at e.value (file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/main.8c016716.chunk.js:1:1265761)
    at e.value (file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/main.8c016716.chunk.js:1:1265333)
    at Ua (file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/2.3575e4b8.chunk.js:2:1670397)
    at Na (file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/2.3575e4b8.chunk.js:2:1670190)
    at gs (file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/2.3575e4b8.chunk.js:2:1706052)
    at uc (file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/2.3575e4b8.chunk.js:2:1697263)
    at sc (file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/2.3575e4b8.chunk.js:2:1697188)
    at Qs (file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/2.3575e4b8.chunk.js:2:1694248)
    at file:///C:/Users/adamb/AppData/Local/Programs/PartyPlanner64/resources/app.asar/static/js/2.3575e4b8.chunk.js:2:1645653
Component Stack Error Details:

    in e
    in div
    in e
    in div
    in e
    in div
    in div
    in div
    in e`

**Comment by PartyPlanner64** [comment]
Was there a particular set of steps leading up to this? I've tried loading Megafruit Island specifically and even overwriting and reloading a ROM with that game in it, but I haven't seen the crash yet.

**Comment by RainbowTHOfficial** [comment]
Not necessarily, and if there was, I don't remember them unfortunately.
